# Application name
spring.application.name=pkms-backend

# Server configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://10.2.177.175:5432/pkms
spring.datasource.username=dbs
spring.datasource.password=12gta#1115
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO
logging.level.com.pkms=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Actuator (??? ???????? ????????)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# CORS Configuration
cors.allowed-origins=http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true

# Test user
app.test-user.username=test
app.test-user.email=test@example.com
app.test-user.name=Test User